# Generated by Django 5.1.3 on 2024-11-26 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_department_employee_delete_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dept',
        ),
    ]
